import { randomUUID } from 'node:crypto'

import { Module } from '@nestjs/common'
import { LoggerModule as PinoLoggerModule } from 'nestjs-pino'

import { APP_CONFIG, type AppConfig } from '../config/index.js'

import { REQUEST_ID_HEADER } from './request-id.js'

@Module({
  imports: [
    PinoLoggerModule.forRootAsync({
      inject: [APP_CONFIG],
      useFactory: (config: AppConfig) => ({
        pinoHttp: {
          level: config.logLevel,
          // The id is generated by Fastify (see app.factory.ts) and echoed in the response header.
          genReqId: (_request, response) => {
            const id = response.getHeader(REQUEST_ID_HEADER)
            return typeof id === 'string' ? id : randomUUID()
          },
          // Never log credentials.
          redact: {
            paths: ['req.headers.authorization', 'req.headers.cookie', 'res.headers["set-cookie"]'],
            censor: '[REDACTED]',
          },
          autoLogging: {
            // Probes run every few seconds; logging them would drown real traffic.
            // Middleware mounting may rewrite `url`, `originalUrl` keeps the real path.
            ignore: (request) => {
              const { originalUrl, url } = request as typeof request & { originalUrl?: string }
              return (originalUrl ?? url ?? '').startsWith('/health')
            },
          },
          ...(config.env === 'development'
            ? { transport: { target: 'pino-pretty', options: { singleLine: true } } }
            : {}),
        },
      }),
    }),
  ],
})
export class LoggerModule {}
